[AI]
# AI 大模型配置
# 支持的模型：OpenAI API、Ollama 本地模型、其他兼容 OpenAI API 的模型

# API 地址（必填）
# OpenAI: https://api.openai.com/v1
# Deepseek: https://api.deepseek.com
# 硅基流动: https://://api.siliconflow.cn/v1
# Ollama: http://127.0.0.1:11434/v1
# SecNN API: https://api.secnn.com/v1
# 其他兼容 OpenAI API 的服务：请查看对应服务的文档
base_url = https://api.secnn.com/v1

# API Key 密钥（可选）
# Ollama: 可以留空
# 其他服务: 根据服务要求填写
api_key = sk-BvsBCejmMIjPj3JVpKb2J7TKchxT2I1i1zqCE1VBgegB1JoI

# 模型名称（必填）
# OpenAI: gpt-3.5-turbo, gpt-4, gpt-4-turbo 等
# Deepseek: deepseek-chat, deepseek-reasoner 等
# 硅基流动: Pro/deepseek-ai/DeepSeek-V3.2-Exp , Qwen/Qwen3.5-397B-A17B 等
# Ollama: deepseek-r1:14b, llama2:7b 等（根据本地安装的模型）
# 其他服务: 根据服务支持的模型填写
model = deepseek-v3.1:671b-cloud
